hospital/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotelmanagement.urls')),
]

hotelmanagement/urls.py
from django.urls import path
from hotelmanagement import views


app_name = 'hotelmanagement'
urlpatterns  = [
    path("index/", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("details/", views.details, name="details"),

]

hotelmanagement/models.py
from django.db import models

# Create your models here.

hotelmanagement/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def index(request):
    return render(request, "hotelmanagement/index.html")


def about(request):
    #return HttpResponse("hi this is giri")
    return render(request, "hotelmanagement/about.html")
    #return HttpResponseRedirect(reverse("hotelmanagement:index"))


def contact(request):
        print(request.POST)
        return render(request, "hotelmanagement/contact.html")


def details(request):
    if request.method == "POST":
        #return HttpResponse("you should render  all details to html page.")
        return render(request,"hotelmanagement/details.html")

hotelmanagement/templates/hotelmanagement/about.html
<h1><B>WELCOME TO FLAIR HOSPITALS</B></h1>
{% load static %}
<img src="{%  static 'hotelmanagement/nature.jpg' %}"><br></br>
 <h1><b>specialities:</b></h1><br>
<h4>1.Allergist.</h4><br>
<h4>2.Anaesthesiology.<h4><br>
    <h4>3.Anesthesia.</h4><br>
     <a href="{% url 'hotelmanagement:index'%}">back </a>

hotelmanagement/templates/hotelmanagement/contact.html
<h1>this is our  contact page</h1>
<h3>EMAIL : <B>flair@hospitals.com</B></h3>
<h3>phone : <B>8885690305</B></h3>
<h3>ADDRESS : <B>d.no:8-256,marathalli,near biriyanizone,KARNATAKA-5163006</B></h3>

<form action="/hotel/contact/" method = "POST">
    {%csrf_token%}
   PATIENT NAME: <input type="text" name="patient name"><br></br>
    PHONE NUMBER: <input type="number" name="patient phone number"><br></br>
    address: <input type="text" name="address"><br></br>
    email: <input type="email" name="email"><br></br>
                <input type="submit" name="submit">


</form>
<a href="{% url 'hotelmanagement:index' %}">back</a>

hotelmanagement/templates/hotelmanagement/details.html
<h1><b>welcome to flair hospitals</b></h1>
<h3>DOCTOR NAME: SIVA REDDY</h3>
<h3>DEGREE: MBBS</h3>
<h3>DESIGNATION: doctor</h3>
{% if data %}
{{data.patient name}}
<a href="{% url 'hotelmanagement:index' %}">back</a>

hotelmanagement/templates/hotelmanagement/index.html
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

li {
  float: left;
}

li a {
  display: block;
  padding: 10px;
  background-color: pink;
}
</style>
<ul>
<li><h1><a href="{% url 'hotelmanagement:about' %}" >about</a></h1></li>
<li><h1><a href="{% url 'hotelmanagement:contact' %}">contact</a></h1></li>
    <li><h1><a href="{% url 'hotelmanagement:details' %}">details</a></h1></li>
</ul>
{% load static %}
<img src="{% static 'hotelmanagement/hospital1.jpg' %}">
<h1><b>welcome to flair hospitals here we have so many fecilities...</b></h1>